### ISSUE TITLE
How to get assets decimals on REST APIs?

### ISSUE THREAD

**Issue by Smillence** [ZigZagExchange/backend#13]
I am trying to use the API in the REST way due to how my code is set up. I am referring to the code at

https://github.com/ZigZagExchange/frontend/blob/master/src/lib/api/providers/APIZKProvider.js#L127

to submit an order. However, the doc says

> The current list of operations available over HTTP POST are: submitorder2, requestquote, orderreceiptreq, refreshliquidity, dailyvolumereq

So it seems there is no way I can get the market info, from which I can retrieve `baseAssetDecimals` and `quoteAssetDecimals` to create arguments for the `syncWallet.getOrder()` call. 

I think the problem is we are not exposing `subscribemarket` to the HTTP POST APIs.

A temporary solution is for me to hardcode the decimals but that feels a bit hacky. Is there a better solution?

cc @taureau75

**Comment by TrooperCrypto** [comment]
You dont have to use our market info. You need to include the zkProvider anyway to sign the order. So you can get the token decimals from there: https://zksync.io/api/sdk/js/utils.html#resolve-token-decimals
This will return the same info as our marketInfo, we just use it to cache the zkSync value. 

Also taureau has implemented a way to get marketInfo over http: https://github.com/ZigZagExchange/backend/commit/548b9ad7c6d698c5ddf3b2cbfa9dfb040a0cf3ff

**Comment by Smillence** [comment]
thanks @TrooperCrypto! this does work for me. I just tested and it worked fine!

But I also noticed a bug in the `submitorder2` REST API. Per the README documentation, it says it returns a `userorderack` message. However, it's not returning a json object with `op` set to 'userorderack'. I only got the args array in my `response.data`

On the other hand, the `requestquote` API works correctly according to the spec which says it returns a `quote` message. When I console.log `response.data`, it prints:


    {"op":"quote","args":[...<REDACTED>...]}

**Comment by TrooperCrypto** [comment]
Good catch. We might change this to be in line with the README and the other returns. Though we have to check if this does not break any integrations. 

I'll tag you here if we do change it.

**Comment by taureau75** [comment]
https://github.com/ZigZagExchange/backend/pull/14

There's an open pull request to fix that issue @Smillence but too many people are using the existing `submitorder2` functionality as is, so we're going to make the change whenever we move to `submitorder3`
