### ISSUE TITLE
submitorder2 stopped working

### ISSUE THREAD

**Issue by agustin125** [ZigZagExchange/backend#157]
Hi, was using the operation "submitorder2" using 
wss://secret-thicket-93345.herokuapp.com/

but as of yesterday it stopped working, it doesn't send error message but it doesn't swap anymore.

**Comment by TrooperCrypto** [comment]
Hey, did you check if the order was created? We use the test server to try new features and our big market maker is a bit unstable at this time. It sometimes crashes and we stop filling orders on rinkeby.

Besides that, we did not change the submitorder2 operation.

**Comment by agustin125** [comment]
okey, thank you very much for your answer.
