### ISSUE TITLE
WebSocket is not open

### ISSUE THREAD

**Issue by July-Jio** [ZigZagExchange/backend#298]
got error below when trying to swap. does anyone know how to fix this?
`throw new Error('WebSocket is not open: readyState 0 (CONNECTING)');`

**Comment by TrooperCrypto** [comment]
Hey, this is the documentation for ws https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

Or take a look at the market maker implementation here: https://github.com/ZigZagExchange/market-maker/blob/e94e7c734e75eb35b43264dd66d06804e1a347d3/marketmaker.js#L113-L116

And also the fuctions: `onWsOpen()`, `onWsClose()` and `handleMessage()`
