### ISSUE TITLE
A little proposal - use Promise.allSettled for improve a bit getERC20Info performance.

### ISSUE THREAD

**Issue by terequell** [ZigZagExchange/backend#697]
Link to place of the code - https://github.com/ZigZagExchange/backend/blob/ef439ba475be483a389109c10a31064cce3dfcc4/src/utils.ts#L90

Explanation: currently you getting tokenInfos step by step (decimals, name, symbol), and you won't get tokenInfos.name while you didnt get contract.decimals. I think it will be a much better use Promise.allSettled here with passing all needed promises to it. The profit is that you'll launch getting three promises in parallel, not step by step as in the current case.

How you can make it (pseudo-code):
const [decimalsRes, nameRes, symbolRes] = await Promise.allSettled([  contract.decimals(), contract.name(), contract.symbol() ]);

Also, i have some syntax proposals for you (like contain some magic values to constants or enums or stuff like that). If you're interested, i can contact with you for help.

**Comment by taureau75** [comment]
Good idea. Saw the PR #697 . I think we're good to merge it.

**Comment by taureau75** [comment]
I guess it's #698 now but same idea.
